name: checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check os version
        run: cat /etc/os-release

      - name: Update & Download
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel xorg-server-xvfb
          
          useradd -m builder
          passwd -d builder
          
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Download
        run: |
          sudo -u builder bash -c '
            cd /tmp
            git clone https://aur.archlinux.org/yay.git
            cd yay
            makepkg -si --noconfirm
            yay -S --noconfirm quickshell wayland wayland-protocols swaylock swww
            
            yay -S --noconfirm qml-niri mpvpaper
          '
      - name: Check xvfb
        run: |
          which xvfb-run
          xvfb-run --help
      - name: Run quickshell
        run: |
          sudo -u builder xvfb-run --server-args="-screen 0 1024x768x24" timeout 5s quickshell ./shell.qmp
        

