name: checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check os version
        run: cat /etc/os-release

      - name: Update & Download
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel
          
          useradd -m builder
          passwd -d builder
          
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Download
        run: |
          cd /tmp
          chown -R builder:builder .
          sudo -u builder git clone https://aur.archlinux.org/yay.git
          cd yay
          sudo -u builder makepkg -si --noconfirm
          sudo -u pacman -S --noconfirm quickshell wayland wayland-protocols swaylock swww
          yay -S --noconfirm qml-niri mpvpaper
          
